ALTER TABLE public.meta_ad_spend
  ADD COLUMN IF NOT EXISTS video_plays INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS video_p25_watched INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS video_p50_watched INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS video_p75_watched INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS video_p100_watched INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS video_thruplays INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS outbound_clicks INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS link_clicks INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS post_engagement INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS landing_page_views INTEGER NOT NULL DEFAULT 0;